test:
  domain: localhost

development:
  domain: "dev.hotchalkember.com:3000"

production:
  domain: "dev.hotchalkember.com"
  # whether this instance of canvas is served over ssl (https) or not
  # defaults to true for production, false for test/development
  ssl: true
  files_domain: "devfiles.hotchalkember.com"
