---
production:
  encryption_key: !binary |-
    ZmUzYzZlOWUyNGI2OTYzMGNmMjBlMzY2ODg2NjkyYmE5MDIyNDIzZTQ0YTNm
    MWE5OTg1ZWI5NDQ0MjFjZWM3ZGUwMmZmMzYxNjNlNzY4NjIxMTc3MDljYzBk
    NTZkOWUzZDY5ODMxNGI5MmVkNDRlYjcxYjRkNDk0YjUwZDhjNWE=
development:
  encryption_key: !binary |-
    Mjc0N2VhZWM3MWE3YmNjNzYyZjMyZjRkZjE4ZGZhZDQ2ODI0N2I2YzcxYjgx
    YjgxOWVmMWMzMWJlYzJkOWY1NGRkOTEyZTI5YzkxMjg5ZTA0MGUyY2JiYTYx
    ZDNmYjkyZTExMDAxMGZiNjg3OTdjYzFmMzJhNjVjMTkxMWNjMDE=
test:
  encryption_key: 12345
